#!/bin/sh

calibrate() {
	TSLIB_TSDEVICE=/dev/input/event0 /usr/bin/ts_calibrate
	touch /etc/.reset-touchscreen-calibration
}

commit() {
	rm -f /home/ftc/.reset-touchscreen-calibration
}

reset() {
	cp -f /media/sdcard/root/etc/pointercal /etc/pointercal
	commit
}

case "$1" in
        calibrate)
                calibrate
                ;;
        commit)
                commit
                ;;

        reset)
                reset
                ;;

        *)
                echo "Usage: $0 {calibrate|commit|reset}"
                exit 1
esac
