#!/bin/busybox sh
/bin/busybox --install -s

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# mount kernel filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mkdir -p /dev/shm

move_kernel_mounts() {
  for dir in proc sys dev; do
    mount -o move $1$dir $2$dir
  done
}

get_opt() {
  echo "$@" | cut -d "=" -f 2
}

init=/sbin/init
root=/dev/mmcblk0p2
for i in $(cat /proc/cmdline); do
  case $i in
    root\=*)
      root=$(get_opt $i)
      ;;
    init\=*)
      init=$(get_opt $i)
      ;;
  esac
done

# mount SD card
mount -t vfat /dev/mmcblk0p1 /sdcard -o dmask=077,fmask=177,sync
if [ -f /sdcard/rootfs.img ]; then
  mount -t auto /sdcard/rootfs.img /newroot -o loop,ro
elif [ -b "$root" ]; then
  mount -t auto "$root" /newroot
else
  echo "No root file system found, dropping to a shell"
  exec /bin/sh
fi

if [ -x "/newroot/$init" ]; then
  mount -o move /sdcard /newroot/media/sdcard
  move_kernel_mounts / /newroot/
  exec switch_root /newroot "${init}"
fi

#This will only be run if the exec above failed
echo "Failed to switch_root or no init found, dropping to a shell"
move_kernel_mounts /newroot/ /
exec /bin/sh
