#!/bin/busybox sh
mount -t vfat /dev/mmcblk1p1 /media/sdcard/boot -o dmask=077,fmask=177,sync

# Hide cursor and show splash screen
echo -e "\033[?25l\033[9;0]\033[14;0]" > /dev/tty1
psplash -n --filename /ftc-firstboot.png -y 212 --BarCol FCCE04 --BarBkCol 347ECC --BkCol 000000 &

fail() {
  psplash-write "QUIT"
  psplash -n --filename /ftc-firstboot-failed.png -y 212 --BarCol FF0000 --BarBkCol 347ECC --BkCol 000000 &
  psplash-write "PROGRESS 100"
  psplash-write "QUIT"
  exit 1
}

progress() {
  psplash-write "PROGRESS $1"
  echo $2
}

# back up system files
mkdir /backup
cp /media/sdcard/boot/uImage /backup || fail
progress 10 "backup uImage"
cp /media/sdcard/boot/am335x-kno_txt.dtb /backup || fail
progress 15 "backup am335x-kno_txt.dtb"
cp /media/sdcard/boot/rootfs.img /backup || fail
progress 45 "backup rootfs.img"
# umount posix-overlay and underlying FAT FS
umount /media/sdcard/boot || fail

# repartition the SD card
fdisk -u /dev/mmcblk1 << EOF || fail
d
n
p
1
2048
1000000
t
c
n
p
2
1000001

w
EOF
progress 50 "repartition sd card"

# Create the new file systems
mkfs.fat -n CFW-BOOT -F 32 /dev/mmcblk1p1 || fail
progress 55 "create FAT fs on partition 1"
echo y | mke2fs -q -t ext4 -L CFW-DATA /dev/mmcblk1p2 || fail
progress 60 "create ext4 fs on partition 2"
# restore backed up files
mount -t vfat /dev/mmcblk1p1 /media/sdcard/boot -o dmask=077,fmask=177 || fail
cp /backup/uImage  /media/sdcard/boot || fail
progress 65 "restore uImage"
cp /backup/am335x-kno_txt.dtb  /media/sdcard/boot || fail
progress 70 "restore am335x-kno_txt.dtb"
cp /backup/rootfs.img /media/sdcard/boot || fail
progress 75 "restore rootfs.img"
if [ -f /backup/rootfs.conf ]; then 
  cp /backup/rootfs.conf /media/sdcard/boot || fail
fi
umount /media/sdcard/boot || fail
progress 95 "restore partition 1 complete"

mount -t ext4 /dev/mmcblk1p2 /media/sdcard/data || fail
mkdir -p /media/sdcard/data/overlay/etc/ || fail
mkdir -p /media/sdcard/data/overlay/.workdir/etc || fail
chmod go-rwx /media/sdcard/data/overlay/ || fail 
mkdir -p /media/sdcard/data/home/ftc/apps || fail
chown -R 1001:1001 /media/sdcard/data/home/ftc || fail
mkdir -p /media/sdcard/data/home/ROBOPro/ROBOProFiles || fail
chown -R 1004:1008 /media/sdcard/data/home/ROBOPro || fail
umount /media/sdcard/data || fail

progress 100 "finished"
psplash-write "QUIT"
