ROOTFS_TXTZIP_OUT_NAME := txt
ROOTFS_TXTZIP_DEPENDENCIES := host-python3 host-zip $(subst $\",,$(BR2_TARGET_ROOTFS_TXTZIP_DEPENDS))

define ROOTFS_TXTZIP_CMD
	BINARIES_DIR=$(BINARIES_DIR) ROOTFS_TXTZIP_DIR=$(ROOTFS_TXTZIP_DIR) python3 $(BR2_EXTERNAL_FTCOMMUNITY_TXT_PATH)/fs/txtzip/build.py
endef


$(eval $(rootfs))
