#!/bin/sh

# disable ASLR. Needed for online some modes of libROBOPRo
echo 0 > /proc/sys/kernel/randomize_va_space

# hide cursor; disable screensaver; disable vesa powerdown
echo -e "\033[?25l\033[9;0]\033[14;0]" > /dev/tty1

# load ftc splash image. Use FT colors for progress bar
psplash -n --filename /etc/ftc-logo.png -y 212 --BarCol FCCE04 --BarBkCol 347ECC --BkCol 000000 &

# load locale if present
if [ -r /etc/locale ]; then
    . /etc/locale
    export LANG LANGUAGE LC_ALL
fi

# count scripts to be executed
SPLASH_MAX=0
SPLASH_LAST=""
for i in /etc/init.d/S??* ;do
     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
     SPLASH_MAX=$((SPLASH_MAX+1))
     SPLASH_LAST="$i"
done

# calculate the step size for the progress bar
SPLASH_STEP=$((100/SPLASH_MAX))

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
SPLASH=0
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     SPLASH=$((SPLASH+SPLASH_STEP))

     if [ "$i" == "$SPLASH_LAST" ] ; then
        psplash-write "PROGRESS 100"
        psplash-write "QUIT"
     else
       psplash-write "PROGRESS $SPLASH"
     fi

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
