#!/bin/sh

check_104() {
    # uid mapping changed for user ROBOPro
    if [ `id -g ROBOPro` != 1008  || `id -u ROBOPro` != 1004 ]; then
	deluser ROBOPro
	delgroup ROBOPro
	addgroup -g 1008 ROBOPro
	adduser -h /opt/fischertechnik -s /bin/sh -G ROBOPro -D -H -u 1004 ROBOPro
	adduser ROBOPro users
	adduser ROBOPro tty
	adduser ROBOPro video
	adduser ROBOPro audio
	adduser ROBOPro i2c
    fi
}

check_105() {
    # ntp user was newly introduced in buildroot 2023.02.3
    if !id -u ntp; then
	adduser -s /bin/false -S -D -H -u 101 -G ntp ntp
    fi
}
    
case "$1" in
    start)
	check_104
	check_105
	;;
esac


	    
