#!/bin/sh

SDCARD=/media/sdcard

is_readonly_fs() {
  egrep -q "$1 ([^ ]+) ro[ ,]" /proc/mounts
  return $?
}

setup_dir() {
	mkdir -p "$SDCARD/$1"
	chown -f "$2" "$SDCARD/$1"
	test -n "$3" && chmod -f "$3" "$SDCARD/$1"
}

case "$1" in
  start) $SDCARD
	chmod -f u=rw,go-rwx $SDCARD/uImage $SDCARD/am335x-kno_txt.dtb $SDCARD/rootfs.img
	setup_dir apps ftc:ftc u=rwx,go=rx
	setup_dir config root:root u=rwx,go=rx
	if is_readonly_fs / ; then
		# Setup writeable overlay of /etc with changes in $SDCARD/config/etc
		setup_dir config/etc root:root u=rwx,go=rx
		mkdir -p /tmp/.etc-readonly
		mount --bind /etc /tmp/.etc-readonly
		unionfs "$SDCARD/config/etc=RW:/tmp/.etc-readonly=RO" /etc -o cow,allow_other,nonempty,hide_meta_files
		# Setup writable /home/ftc with changes in $SDCARD/data
		setup_dir data ftc:ftc u=rwx,go=rx
		mount --bind "$SDCARD/data" /home/ftc
	fi
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

