#!/bin/sh
#
# Attach UBI partitions
#

case "$1" in
  start)
    /usr/sbin/ubiattach -p /dev/mtd10 -d0
    ;;
  stop)
    /usr/sbin/ubidetach -p /dev/mtd10
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit $?

