#!/bin/sh


NAME=sound

start() {
        printf "Starting $NAME: "
        modprobe snd-aloop pcm_substreams=1
        killall arecord
        arecord -c1 -r22050 -twav -D plug:asnoop 2>/dev/null | txt_snd_cat &
        echo "OK"
}

stop() {
        printf "Stopping $NAME: "
        killall arecord
        echo "OK"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
