#!/bin/sh

start() {
  if [ -f /home/ftc/.reset-touchscreen-calibration ]; then
    calibrate-touchscreen reset
  fi
}

stop() {}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start}"
                exit 1
esac
