#!/bin/sh

start() {
  if [ -f /home/ftc/.reset-touchscreen-calibration ]; then
    cp /media/sdcard/root/etc/pointercal /etc/pointercal
    /sbin/unset-touchscreen-calibration-reset-flag
  fi
}

stop() {}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start}"
                exit 1
esac
