#!/bin/sh

start() {
  if [ -f /etc/reset-touchscreen-calibration ]; then
    cp /media/sdcard/root/etc/pointercal /etc/pointercal
    rm /etc/reset-touchscreen-calibration
  fi
}

stop() {}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start}"
                exit 1
esac
