#!/bin/sh

NAME=x11vnc
PIDFILE=/var/run/$NAME.pid
ENABLED=no

conffile=/etc/default/x11vnc
# to enable, add ENABLED=yes to $conffile
[ -f $conffile ] && . $conffile

start() {
    if [ $ENABLED -eq "yes" ]; then
        printf "Starting $NAME: "
        start-stop-daemon --start -c ftc --make-pidfile --background --pidfile $PIDFILE \
			  --exec x11vnc -- -display :0 -forever \
            && echo "OK" || echo "FAIL"
    fi
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
	rm -f $PIDFILE
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
