#!/bin/sh
#
# Starts Xorg
#

BIN=/usr/bin/Xorg
PIDFILE=/var/run/xorg.pid

LAUNCHER_CONFIG=/etc/default/launcher
XORG_CONF=/etc/X11/xorg.conf
SCREEN_ROTATION=0
[ -e $LAUNCHER_CONFIG ] && . $LAUNCHER_CONFIG
use_config() {
    config=$XORG_CONF.$1
    if ! diff -N -q $XORG_CONF $config; then
	cp -f $config $XORG_CONF
    fi
}
case $SCREEN_ROTATION in
90)  use_config cw;;
180) use_config ud;;
270) use_config ccw;;
*)   use_config up;;
esac


# ":0.0 vt01" makes sure Xorg finds the correct terminal.
# -nocursor hides the mouse pointer
XORG_ARGS=":0.0 vt01 -s 0 -nocursor"

start() {
	printf "Starting Xorg: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec xinit -- /etc/X11/xinit/xinitrc -- $BIN $XORG_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping Xorg: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
