#!/bin/sh

NAME=launcher
PIDFILE=/var/run/$NAME.pid

if [ -r /etc/default/launcher ]; then
  while read line ; do
    case "$line" in
      "SCREEN_ROTATION=0") SCREEN_ROTATION=0 ;;
      "SCREEN_ROTATION=90") SCREEN_ROTATION=90 ;;
      "SCREEN_ROTATION=180") SCREEN_ROTATION=180 ;;
      "SCREEN_ROTATION=270") SCREEN_ROTATION=270 ;;
      *) echo "Ignoring unknown configuration entry: $line" ;;
    esac
  done < /etc/default/launcher
fi

export PYTHONPYCACHEPREFIX=/home/ftc/.pycache
export PYTHONPATH=/opt/ftc
export DISPLAY=:0
export TSLIB_TSDEVICE=/dev/input/event0
export QT_QPA_PLATFORM=xcb


start() {
        printf "Starting $NAME: "
        start-stop-daemon --start -c ftc --background --make-pidfile --pidfile $PIDFILE \
              --exec /opt/ftc/launcher.py \
              && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $NAME: "
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE \
                && echo "OK" || echo "FAIL"
	rm -f $PIDFILE
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
