#!/bin/sh
#
# start/stop TxtControlMain
#

start_txtcontrol() {
    if pidof run-txtcontrol >/dev/null ; then
        kill_txtcontrol
    else
        screen -A -m -d -S ROBOPRO /opt/fischertechnik/run-txtcontrol
    fi
}

kill_txtcontrol() {
    killall -q -QUIT TxtControlMain
    killall -q -TERM TxtControlMain
    killall -q -TERM TxtControlMain
}

case "$1" in
  start|start-service)
    touch /run/txtcontrol-service
    start_txtcontrol
    ;;
  stop-service)
    rm -f /run/txtcontrol-service
    kill_txtcontrol
    ;;
  start-main)
    touch /run/txtcontrol-app
    start_txtcontrol
    ;;
  stop-main)
    rm -f /run/txtcontrol-app
    kill_txtcontrol
    ;;
  stop)
    rm -f /run/txtcontrol-app
    rm -f /run/txtcontrol-service
    kill_txtcontrol
    ;;
  restart)
    kill_txtcontrol
    start_txtcontrol
    ;;
  *)
    echo "Usage: $0 {start|stop|start-main|stop-main}"
    exit 1
esac

exit $?

